use kindergan2;

drop table attendance;

CREATE TABLE IF NOT EXISTS attendance (
    uid INT(11) PRIMARY KEY AUTO_INCREMENT,
    kindergan_name VARCHAR(20) NOT NULL,
    class INT(1) NOT NULL,
    parent_id VARCHAR(10) NOT NULL,
    name VARCHAR(25) NOT NULL,
    1st TINYINT(1) DEFAULT FALSE,
    2nd TINYINT(1) DEFAULT FALSE,
    3rd TINYINT(1) DEFAULT FALSE,
    4th TINYINT(1) DEFAULT FALSE,
    5th TINYINT(1) DEFAULT FALSE,
    6th TINYINT(1) DEFAULT FALSE,
    7th TINYINT(1) DEFAULT FALSE,
    8th TINYINT(1) DEFAULT FALSE,
    9th TINYINT(1) DEFAULT FALSE,
    10th TINYINT(1) DEFAULT FALSE,
    11th TINYINT(1) DEFAULT FALSE,
    12th TINYINT(1) DEFAULT FALSE,
    13th TINYINT(1) DEFAULT FALSE,
    14th TINYINT(1) DEFAULT FALSE,
    15th TINYINT(1) DEFAULT FALSE,
    16th TINYINT(1) DEFAULT FALSE,
    17th TINYINT(1) DEFAULT FALSE,
    18th TINYINT(1) DEFAULT FALSE,
    19th TINYINT(1) DEFAULT FALSE,
    20th TINYINT(1) DEFAULT FALSE,
    21st TINYINT(1) DEFAULT FALSE,
    22nd TINYINT(1) DEFAULT FALSE,
    23rd TINYINT(1) DEFAULT FALSE,
    24th TINYINT(1) DEFAULT FALSE,
    25th TINYINT(1) DEFAULT FALSE,
    26th TINYINT(1) DEFAULT FALSE,
    27th TINYINT(1) DEFAULT FALSE,
    28th TINYINT(1) DEFAULT FALSE,
    29th TINYINT(1) DEFAULT FALSE,
    30th TINYINT(1) DEFAULT FALSE,
    31st TINYINT(1) DEFAULT FALSE
);

ALTER TABLE attendance AUTO_INCREMENT = 1;